/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WordGame;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class GameStart {
    public static void main(String[] args){
        SpringApplication.run(GameStart.class, args);
    }
}
